# Generated by Django 6.0.1 on 2026-02-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarydocument',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.course'),
        ),
    ]
