# Generated by Django 6.0.1 on 2026-04-06 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_coursegroupmessage_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coin_price',
            field=models.PositiveIntegerField(default=0, help_text='Price in LMS Coins (if purchasable)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_coin_purchasable',
            field=models.BooleanField(default=False, help_text='Check this to allow purchasing with coins'),
        ),
        migrations.AddField(
            model_name='coursegroupmessage',
            name='bounty_amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount offered for solving this question'),
        ),
        migrations.AddField(
            model_name='coursegroupmessage',
            name='bounty_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_bounties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursegroupmessage',
            name='is_bounty_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursegroupmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lms_coins',
            field=models.PositiveIntegerField(default=100, help_text='Virtual coins for LMS Economy'),
        ),
    ]
