# Generated by Django 6.0.1 on 2026-05-03 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_dynamicbountyproblem_bountysubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_faculty': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_faculty',
            field=models.BooleanField(default=False, verbose_name='Is Faculty'),
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('specialization', models.CharField(blank=True, help_text='e.g., Data Science, AI, Backend', max_length=200, null=True)),
                ('background', models.CharField(blank=True, help_text='e.g., Science, Arts', max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_faculty': True}, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
